server:
  port: 8761

eureka:
  instance:
    hostname: 127.0.0.1
  client:
#    registerWithEureka: false
#    fetchRegistry: false
    serviceUrl:
      defaultZone: http://127.0.0.1:8760/eureka/

spring:
  application:
    name: eurka-server